version: '3.8'
services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "5555:5555"
    command: npm run dev
    environment:
      DATABASE_URL: "postgresql://kamunity_user:kamunity_password@db:5432/kamunity_db?schema=public"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kamunity_user
      POSTGRES_PASSWORD: kamunity_password
      POSTGRES_DB: kamunity_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
