[build]
  publish = ".next"
  command = "npm run build"
  environment = { DISABLE_ESLINT = "true" }

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_DEMO_MODE = "true"
  NEXT_PUBLIC_MAX_CONCURRENT_USERS = "100"
