[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  DISABLE_ESLINT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_DEMO_MODE = "true"
  NEXT_PUBLIC_MAX_CONCURRENT_USERS = "100"
